/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminTrialReadinessRouteImport } from './routes/admin.trial-readiness'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminRenewalsRouteImport } from './routes/admin.renewals'
import { Route as AdminReliabilityRouteImport } from './routes/admin.reliability'
import { Route as AdminPhotosRouteImport } from './routes/admin.photos'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminManualAssignmentRouteImport } from './routes/admin.manual-assignment'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCustomerMapRouteImport } from './routes/admin.customer-map'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AdminServiceIdRouteImport } from './routes/admin.service.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AuthenticatedAppTrainingRouteImport } from './routes/_authenticated/app.training'
import { Route as AuthenticatedAppRewardsRouteImport } from './routes/_authenticated/app.rewards'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppMyAssignmentRouteImport } from './routes/_authenticated/app.my-assignment'
import { Route as AuthenticatedAppLiveRouteImport } from './routes/_authenticated/app.live'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppEarningsRouteImport } from './routes/_authenticated/app.earnings'
import { Route as AuthenticatedAppAssignmentsRouteImport } from './routes/_authenticated/app.assignments'
import { Route as AuthenticatedAppAreaRouteImport } from './routes/_authenticated/app.area'
import { Route as AuthenticatedAppServiceIdRouteImport } from './routes/_authenticated/app.service.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrialReadinessRoute = AdminTrialReadinessRouteImport.update({
  id: '/trial-readiness',
  path: '/trial-readiness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRenewalsRoute = AdminRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReliabilityRoute = AdminReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManualAssignmentRoute = AdminManualAssignmentRouteImport.update({
  id: '/manual-assignment',
  path: '/manual-assignment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerMapRoute = AdminCustomerMapRouteImport.update({
  id: '/customer-map',
  path: '/customer-map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AdminServiceIdRoute = AdminServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AuthenticatedAppTrainingRoute =
  AuthenticatedAppTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRewardsRoute = AuthenticatedAppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMyAssignmentRoute =
  AuthenticatedAppMyAssignmentRouteImport.update({
    id: '/my-assignment',
    path: '/my-assignment',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLiveRoute = AuthenticatedAppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEarningsRoute =
  AuthenticatedAppEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssignmentsRoute =
  AuthenticatedAppAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAreaRoute = AuthenticatedAppAreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServiceIdRoute =
  AuthenticatedAppServiceIdRouteImport.update({
    id: '/service/$id',
    path: '/service/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/customer-map': typeof AdminCustomerMapRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/manual-assignment': typeof AdminManualAssignmentRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/reliability': typeof AdminReliabilityRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trial-readiness': typeof AdminTrialReadinessRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/area': typeof AuthenticatedAppAreaRoute
  '/app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/app/earnings': typeof AuthenticatedAppEarningsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/live': typeof AuthenticatedAppLiveRoute
  '/app/my-assignment': typeof AuthenticatedAppMyAssignmentRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/training': typeof AuthenticatedAppTrainingRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/service/$id': typeof AdminServiceIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/service/$id': typeof AuthenticatedAppServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/customer-map': typeof AdminCustomerMapRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/manual-assignment': typeof AdminManualAssignmentRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/reliability': typeof AdminReliabilityRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trial-readiness': typeof AdminTrialReadinessRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin': typeof AdminIndexRoute
  '/app/area': typeof AuthenticatedAppAreaRoute
  '/app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/app/earnings': typeof AuthenticatedAppEarningsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/live': typeof AuthenticatedAppLiveRoute
  '/app/my-assignment': typeof AuthenticatedAppMyAssignmentRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/training': typeof AuthenticatedAppTrainingRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/service/$id': typeof AdminServiceIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/service/$id': typeof AuthenticatedAppServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/customer-map': typeof AdminCustomerMapRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/manual-assignment': typeof AdminManualAssignmentRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/reliability': typeof AdminReliabilityRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trial-readiness': typeof AdminTrialReadinessRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/app/area': typeof AuthenticatedAppAreaRoute
  '/_authenticated/app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/_authenticated/app/earnings': typeof AuthenticatedAppEarningsRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/live': typeof AuthenticatedAppLiveRoute
  '/_authenticated/app/my-assignment': typeof AuthenticatedAppMyAssignmentRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/_authenticated/app/training': typeof AuthenticatedAppTrainingRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/service/$id': typeof AdminServiceIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/service/$id': typeof AuthenticatedAppServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/app'
    | '/admin/attendance'
    | '/admin/customer-map'
    | '/admin/customers'
    | '/admin/fraud'
    | '/admin/import'
    | '/admin/live'
    | '/admin/manual-assignment'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/photos'
    | '/admin/reliability'
    | '/admin/renewals'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/trial-readiness'
    | '/admin/wallet'
    | '/admin/'
    | '/app/area'
    | '/app/assignments'
    | '/app/earnings'
    | '/app/history'
    | '/app/live'
    | '/app/my-assignment'
    | '/app/profile'
    | '/app/rewards'
    | '/app/training'
    | '/admin/customers/$id'
    | '/admin/service/$id'
    | '/app/'
    | '/app/service/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/attendance'
    | '/admin/customer-map'
    | '/admin/customers'
    | '/admin/fraud'
    | '/admin/import'
    | '/admin/live'
    | '/admin/manual-assignment'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/photos'
    | '/admin/reliability'
    | '/admin/renewals'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/trial-readiness'
    | '/admin/wallet'
    | '/admin'
    | '/app/area'
    | '/app/assignments'
    | '/app/earnings'
    | '/app/history'
    | '/app/live'
    | '/app/my-assignment'
    | '/app/profile'
    | '/app/rewards'
    | '/app/training'
    | '/admin/customers/$id'
    | '/admin/service/$id'
    | '/app'
    | '/app/service/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/app'
    | '/admin/attendance'
    | '/admin/customer-map'
    | '/admin/customers'
    | '/admin/fraud'
    | '/admin/import'
    | '/admin/live'
    | '/admin/manual-assignment'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/photos'
    | '/admin/reliability'
    | '/admin/renewals'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/trial-readiness'
    | '/admin/wallet'
    | '/admin/'
    | '/_authenticated/app/area'
    | '/_authenticated/app/assignments'
    | '/_authenticated/app/earnings'
    | '/_authenticated/app/history'
    | '/_authenticated/app/live'
    | '/_authenticated/app/my-assignment'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/rewards'
    | '/_authenticated/app/training'
    | '/admin/customers/$id'
    | '/admin/service/$id'
    | '/_authenticated/app/'
    | '/_authenticated/app/service/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trial-readiness': {
      id: '/admin/trial-readiness'
      path: '/trial-readiness'
      fullPath: '/admin/trial-readiness'
      preLoaderRoute: typeof AdminTrialReadinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/renewals': {
      id: '/admin/renewals'
      path: '/renewals'
      fullPath: '/admin/renewals'
      preLoaderRoute: typeof AdminRenewalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reliability': {
      id: '/admin/reliability'
      path: '/reliability'
      fullPath: '/admin/reliability'
      preLoaderRoute: typeof AdminReliabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manual-assignment': {
      id: '/admin/manual-assignment'
      path: '/manual-assignment'
      fullPath: '/admin/manual-assignment'
      preLoaderRoute: typeof AdminManualAssignmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-map': {
      id: '/admin/customer-map'
      path: '/customer-map'
      fullPath: '/admin/customer-map'
      preLoaderRoute: typeof AdminCustomerMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/admin/service/$id': {
      id: '/admin/service/$id'
      path: '/service/$id'
      fullPath: '/admin/service/$id'
      preLoaderRoute: typeof AdminServiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/_authenticated/app/training': {
      id: '/_authenticated/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AuthenticatedAppTrainingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rewards': {
      id: '/_authenticated/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AuthenticatedAppRewardsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/my-assignment': {
      id: '/_authenticated/app/my-assignment'
      path: '/my-assignment'
      fullPath: '/app/my-assignment'
      preLoaderRoute: typeof AuthenticatedAppMyAssignmentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/live': {
      id: '/_authenticated/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AuthenticatedAppLiveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/earnings': {
      id: '/_authenticated/app/earnings'
      path: '/earnings'
      fullPath: '/app/earnings'
      preLoaderRoute: typeof AuthenticatedAppEarningsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assignments': {
      id: '/_authenticated/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AuthenticatedAppAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/area': {
      id: '/_authenticated/app/area'
      path: '/area'
      fullPath: '/app/area'
      preLoaderRoute: typeof AuthenticatedAppAreaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/service/$id': {
      id: '/_authenticated/app/service/$id'
      path: '/service/$id'
      fullPath: '/app/service/$id'
      preLoaderRoute: typeof AuthenticatedAppServiceIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAreaRoute: typeof AuthenticatedAppAreaRoute
  AuthenticatedAppAssignmentsRoute: typeof AuthenticatedAppAssignmentsRoute
  AuthenticatedAppEarningsRoute: typeof AuthenticatedAppEarningsRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppLiveRoute: typeof AuthenticatedAppLiveRoute
  AuthenticatedAppMyAssignmentRoute: typeof AuthenticatedAppMyAssignmentRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRewardsRoute: typeof AuthenticatedAppRewardsRoute
  AuthenticatedAppTrainingRoute: typeof AuthenticatedAppTrainingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppServiceIdRoute: typeof AuthenticatedAppServiceIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAreaRoute: AuthenticatedAppAreaRoute,
  AuthenticatedAppAssignmentsRoute: AuthenticatedAppAssignmentsRoute,
  AuthenticatedAppEarningsRoute: AuthenticatedAppEarningsRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppLiveRoute: AuthenticatedAppLiveRoute,
  AuthenticatedAppMyAssignmentRoute: AuthenticatedAppMyAssignmentRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRewardsRoute: AuthenticatedAppRewardsRoute,
  AuthenticatedAppTrainingRoute: AuthenticatedAppTrainingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppServiceIdRoute: AuthenticatedAppServiceIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCustomerMapRoute: typeof AdminCustomerMapRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminFraudRoute: typeof AdminFraudRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminManualAssignmentRoute: typeof AdminManualAssignmentRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminReliabilityRoute: typeof AdminReliabilityRoute
  AdminRenewalsRoute: typeof AdminRenewalsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrialReadinessRoute: typeof AdminTrialReadinessRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminServiceIdRoute: typeof AdminServiceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCustomerMapRoute: AdminCustomerMapRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminFraudRoute: AdminFraudRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminManualAssignmentRoute: AdminManualAssignmentRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminReliabilityRoute: AdminReliabilityRoute,
  AdminRenewalsRoute: AdminRenewalsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrialReadinessRoute: AdminTrialReadinessRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminServiceIdRoute: AdminServiceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
