export const Constants = {
    public: {
        Enums: {
            app_role: ["admin", "supervisor", "partner", "customer", "ops_manager"],
            availability_status: ["online", "offline", "leave", "emergency_leave"],
            benefit_type: [
                "interior",
                "exterior_daily",
                "exterior_hydrophobic",
                "dusting",
                "tyre_polish",
                "paper_mats",
                "fragrance",
            ],
            complaint_status: ["open", "investigating", "resolved", "dismissed"],
            partner_status: [
                "pending_verification",
                "active",
                "suspended",
                "offline",
            ],
            payout_status: ["pending", "processing", "paid", "failed"],
            photo_angle: ["front", "rear", "left", "right"],
            photo_stage: ["before", "after", "unavailable", "dirty"],
            reliability_event_type: [
                "assignment_accepted",
                "service_completed",
                "on_time_service",
                "customer_complaint",
                "missed_service",
                "assignment_cancelled",
                "repeated_unavailability",
            ],
            service_status: [
                "pending",
                "in_progress",
                "completed",
                "unavailable",
                "skipped",
                "covered_by_booking",
            ],
            subscription_plan: [
                "daily_shine_monthly",
                "daily_shine_quarterly",
                "daily_shine_yearly",
            ],
            unavailable_reason: [
                "vehicle_not_available",
                "parking_locked",
                "customer_asked_to_skip",
                "access_not_available",
                "customer_not_responding",
                "dirty_vehicle",
                "vehicle_taken_out",
                "keys_not_available",
                "security_guard_denied",
                "other",
            ],
        },
    },
};
